[project]
name = "ai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "bunq-sdk>=1.28.0",
    "fastapi-mcp>=0.3.3",
    "fastapi[standard]>=0.115.12",
    "google-genai>=1.13.0",
    "google-generativeai>=0.3.2",
    "pydantic>=2.11.4",
    "pydantic-ai>=0.1.9",
    "python-dotenv>=1.1.0",
    "streamlit>=1.45.0",
]

[dependency-groups]
dev = [
    "ruff>=0.11.8",
]
